[versions]
junit-bom = "6.0.1"
mockito-bom = "5.20.0"
assertj-bom = "3.27.6"

[libraries]
# junit
org-junit-junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }
org-junit-jupiter-junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
org-junit-platform-junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
# mockito
org-mockito-mockito-bom = { module = "org.mockito:mockito-bom", version.ref = "mockito-bom" }
org-mockito-mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter" }
# assertj
org-assertj-assertj-bom = { module = "org.assertj:assertj-bom", version.ref = "assertj-bom" }
org-assertj-assertj-core = { module = "org.assertj:assertj-core" }

[bundles]
test-util = [
    "org-assertj-assertj-core",
    "org-junit-jupiter-junit-jupiter",
    "org-mockito-mockito-junit-jupiter",
]
